# n=int(input('Digite um número: '))
# print('O número informado foi: ',n)
# print('Alo mundo')
# m=int(input('Digite um número: '))
# n=int(input('Digite outro: '))
# print('A soma dos números dados é: ',n+m)
# n1=float(input('Digite a nota 1 '))
# n2=float(input('Digite a nota 2 '))
# n3=float(input('Digite a nota 3 '))
# n4=float(input('Digite a nota 4 '))
# print('A média final é: ',(n1+n2+n3+n4)/4)
# m=float(input('Quantos m? '))
# con=m*100
# print(m,'m é igual a: %2.0f cm'%con)
# r=int(input('Qual o raio do círculo '))
# print('A área da circunferência é: ',3.14*(r**2))
# l=int(input('Digite o valor do lado do quadrado em cm² '))
# a=((l**2)*2)
# print('A área do quadrado x2 é igual a %icm²:'%a)
# g=float(input("Quanto ganha por hora trabalhada? "))
# h=float(input('Quantas horas trabalhadas no mês?'))
# sal=g*h
# print('O salário no final do mês é de: R$%2.2f'%sal)