# # a=input('escreva o que quiser: ')
# # print(len(a))
# # b=input('digite: ')
# # c=input('digite: ')
# # print(b,len(b))
# # print('{0}',len(c),''.format(c))
# # n=input('say your name: ')
# # print(n[:4])
# m=input('say your name: ')
# print(m.capitalize())
nam=input('Whereas say your name\n')
print(nam[:9].capitalize())