n=input('Nome:')
c=input('CPF:')
r=input('RG:')
d=input('Data de nascimento:')
s=input('Sexo:')
p=input('Peso:')
ts=input('Tipo sanguíneo:')
r=input('Renda:')
e=input('Endereço:')
t=input('Telefone:')
c=input('Cidade:')
e=input('Estado:')
print('nome:',n,'\nCPF:',c,'\nRG:',r,'\nData de nascimento:',d,'\nSexo:',s,'\nPeso: (kg)',p,'\nTipo sanguíneo:',ts,'\nRenda:',r,'\nEndereço:',e,'\nTelefone:',t,'\nCidade:',c,'\nEstado:',e)